import { defineStore } from "pinia";
import { get_request, create_request } from "../services/request_http";

/**
 * Store to handle Google reCAPTCHA in the frontend.
 * 1. Fetches the public site-key from the backend.
 * 2. Sends the user token to the backend for verification.
 */
export const useCaptchaStore = defineStore("captcha", {
  state: () => ({
    siteKey: null,
    verified: false,
  }),
  actions: {
    /**
     * Fetches the site-key from the backend and stores it.
     * @returns {Promise<string>} The public reCAPTCHA site key.
     */
    async fetchSiteKey() {
      if (this.siteKey) return this.siteKey; // Ya la tenemos

      try {
        const response = await get_request("google-captcha/site-key/");
        this.siteKey = response.data.site_key;
        return this.siteKey;
      } catch (error) {
        console.error("Error fetching site key:", error);
        throw error;
      }
    },

    /**
     * Sends the token to the backend to verify it with Google.
     * @param {string} token Token generated by Google reCAPTCHA.
     * @returns {Promise<boolean>} true if the token is valid.
     */
    async verify(token) {
      if (!token) return false;
      try {
        const response = await create_request("google-captcha/verify/", {
          token,
        });
        this.verified = response.data.success === true;
        return this.verified;
      } catch (error) {
        console.error("Error verifying reCAPTCHA:", error);
        this.verified = false;
        return false;
      }
    },

    reset() {
      this.verified = false;
    },
  },
}); 