// Audit index, not displayed to users. IDs connect real screens to explanatory nodes.
// Relative paths below belong to nested routes in router/index.js.
export const routeInventory = {
  '/sign_in': 'authentication-login-email',
  '/home': 'help-privacy',
  '/sign_on': 'authentication-register',
  '/forget_password': 'authentication-register',
  '/policies/privacy_policy': 'help-privacy',
  '/policies/terms_of_use': 'help-terms',
  '/no_connection': 'help-offline',
  '/subscriptions': 'subscriptions-view-plans',
  '/checkout/:plan': 'subscriptions-checkout',
  '/subscription/sign_in': 'subscriptions-checkout',
  '/subscription/sign_up': 'subscriptions-checkout',
  '/dashboard': 'dashboard',
  '/notifications': 'notifications',
  '/process_list/:user_id?/:display?': 'processes',
  '/process_detail/:process_id/:display?': 'processes-process-historical',
  '/process_form/:action/:process_id?': 'processes-create-process',
  '/directory_list': 'directory',
  '/legal_request': 'requests-create-request',
  '/legal_requests': 'requests',
  '/legal_request_create': 'requests-create-request',
  '/legal_request_detail/:id': 'requests-request-thread',
  '/services': 'services',
  '/services/:id': 'services-services-dynamic-form',
  '/service_requests/my': 'services-services-my-requests',
  '/services_list': 'services',
  '/my_requests': 'services-services-my-requests',
  '/service_requests/inbox': 'inbox',
  '/service_requests/:id': 'services-services-my-requests',
  '/services_admin': 'administration-admin-services-catalog',
  '/data_reassignment': 'administration-admin-data-reassignment',
  '/intranet_g_y_m': 'intranet',
  '/schedule_appointment': 'appointments',
  '/organizations_dashboard': 'organizations',
  '/dynamic_document_dashboard': 'documents',
  'signed-documents': 'documents-electronic-signature',
  'lawyer/editor/create/:title': 'documents-lawyer-tabs',
  'lawyer/editor/edit/:id': 'documents-lawyer-tabs',
  'client/editor/edit/:id': 'documents-client-use-document',
  'document/use/:mode/:id/:title': 'documents-client-use-document',
  'lawyer/variables-config': 'documents-lawyer-tabs',
  '/secop': 'secop',
  ':id': 'secop-secop-process-detail',
  '/user_guide': 'help-manual',
};

export const nonScreenRoutes = {
  '': 'Layout children reuse their parent screen.',
  '/': 'Authentication-aware redirect.',
  '/auth/google/callback': 'Authentication callback, not a browsable module.',
  '/:pathMatch(.*)*': 'Unknown-route redirect.',
};
