import { mount } from "@vue/test-utils";
import { createPinia, setActivePinia } from "pinia";

import { useDynamicDocumentStore } from "@/stores/dynamic_document";
import { useUserStore } from "@/stores/auth/user";

import DocumentVariablesConfig from "@/views/dynamic_document/DocumentVariablesConfig.vue";

const mockShowNotification = jest.fn();
const mockRouterPush = jest.fn();
const mockSwalFire = jest.fn().mockResolvedValue({});

jest.mock("@/shared/notification_message", () => ({
  __esModule: true,
  showNotification: (...args) => mockShowNotification(...args),
}));

jest.mock("sweetalert2", () => ({
  __esModule: true,
  default: { fire: (...args) => mockSwalFire(...args) },
}));

jest.mock("vue-router", () => ({
  useRouter: () => ({ push: mockRouterPush }),
}));

jest.mock("@heroicons/vue/24/outline", () => {
  const Stub = { name: "IconStub", template: "<span />" };
  return {
    __esModule: true,
    PlusIcon: Stub,
    PencilIcon: Stub,
    TrashIcon: Stub,
    XMarkIcon: Stub,
  };
});

jest.mock(
  "@/components/dynamic_document/lawyer/document-config/DocumentPermissionsManager.vue",
  () => ({
    __esModule: true,
    default: {
      name: "DocumentPermissionsManager",
      template: "<div />",
      props: ["document"],
      methods: {
        getPermissionsDataExpanded() {
          return { is_public: false, visibility_user_ids: [], usability_user_ids: [] };
        },
      },
    },
  })
);

jest.mock(
  "@/components/dynamic_document/lawyer/document-config/DocumentTagsManager.vue",
  () => ({
    __esModule: true,
    default: {
      name: "DocumentTagsManager",
      template: "<div />",
      props: ["document"],
      methods: {
        getTagIds() {
          return [];
        },
      },
    },
  })
);

const flushPromises = () => new Promise((resolve) => setTimeout(resolve, 0));

function buildVariables() {
  return [
    { name_en: "ClientName", name_es: "Nombre Cliente", field_type: "input", value: "", tooltip: "", summary_field: "none" },
    { name_en: "Amount", name_es: "Monto", field_type: "number", value: "", tooltip: "", summary_field: "none" },
    { name_en: "Category", name_es: "Categoría", field_type: "select", value: "", tooltip: "", summary_field: "none", select_options: ["A", "B"], select_options_text: "A, B" },
  ];
}

function setupStore(pinia, overrides = {}) {
  const store = useDynamicDocumentStore();
  const userStore = useUserStore();

  store.selectedDocument = {
    id: 1,
    title: "Test Template",
    content: "<p>Content</p>",
    variables: overrides.variables || buildVariables(),
    tags: [],
    ...overrides,
  };

  jest.spyOn(store, "fetchDocumentById").mockResolvedValue(store.selectedDocument);
  jest.spyOn(store, "updateDocument").mockResolvedValue({});
  jest.spyOn(store, "createDocument").mockResolvedValue({ id: 99 });
  jest.spyOn(store, "init").mockResolvedValue();

  userStore.currentUser = { id: 5, role: "lawyer" };

  return { store, userStore };
}

async function mountComponent(pinia) {
  const wrapper = mount(DocumentVariablesConfig, {
    global: { plugins: [pinia] },
  });
  await flushPromises();
  return wrapper;
}

describe("DocumentVariablesConfig.vue", () => {
  let pinia;

  beforeEach(() => {
    pinia = createPinia();
    setActivePinia(pinia);
    jest.clearAllMocks();
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  test("renders document title and all variable sections", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.text()).toContain("Test Template");
    expect(wrapper.text()).toContain("ClientName");
    expect(wrapper.text()).toContain("Amount");
    expect(wrapper.text()).toContain("Category");
  });

  test("renders name_es input for each variable", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    // quality: allow-fragile-selector (stable DOM ids generated by component for each variable)
    expect(wrapper.find("#name_es_0").exists()).toBe(true);
    expect(wrapper.find("#name_es_0").element.value).toBe("Nombre Cliente");

    expect(wrapper.find("#name_es_1").exists()).toBe(true);
    expect(wrapper.find("#name_es_1").element.value).toBe("Monto");

    expect(wrapper.find("#name_es_2").exists()).toBe(true);
    expect(wrapper.find("#name_es_2").element.value).toBe("Categoría");
  });

  test("field type selector renders all 6 options", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const selects = wrapper.findAll("#field_type"); // quality: allow-fragile-selector (stable DOM id)
    expect(selects.length).toBeGreaterThanOrEqual(1);

    const options = selects[0].findAll("option");
    const values = options.map((o) => o.element.value);
    expect(values).toEqual(
      expect.arrayContaining(["input", "text_area", "number", "date", "email", "select"])
    );
  });

  test("summary field classification selector renders all options", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const summarySelect = wrapper.find("#summary_field_0"); // quality: allow-fragile-selector (stable DOM id)
    expect(summarySelect.exists()).toBe(true);

    const options = summarySelect.findAll("option");
    const values = options.map((o) => o.element.value);
    expect(values).toEqual(
      expect.arrayContaining(["none", "counterparty", "object", "value", "term", "subscription_date", "start_date", "end_date"])
    );
  });

  test("currency selector appears only when summary_field is 'value'", async () => {
    const variables = buildVariables();
    variables[1].summary_field = "value";
    setupStore(pinia, { variables });
    const wrapper = await mountComponent(pinia);

    // quality: allow-fragile-selector (stable DOM ids for currency selectors)
    expect(wrapper.find("#currency_1").exists()).toBe(true);
    expect(wrapper.find("#currency_0").exists()).toBe(false);
  });

  test("currency selector is hidden when summary_field is not 'value'", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    // quality: allow-fragile-selector (stable DOM ids for currency selectors)
    expect(wrapper.find("#currency_0").exists()).toBe(false);
    expect(wrapper.find("#currency_1").exists()).toBe(false);
  });

  test("select options input appears only for select field type", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const selectOptionsInputs = wrapper.findAll('input[placeholder="Opción 1, Opción 2, Opción 3"]');
    expect(selectOptionsInputs.length).toBe(1);
  });

  test("save as draft button is visible", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const draftBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Guardar como borrador")
    );
    expect(draftBtn).toBeTruthy();
  });

  test("publish button is visible", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const publishBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Publicar")
    );
    expect(publishBtn).toBeTruthy();
  });

  test("cancel button navigates back to dashboard", async () => {
    setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const cancelBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Cancelar")
    );
    expect(cancelBtn).toBeTruthy();

    await cancelBtn.trigger("click");
    await flushPromises();

    expect(mockRouterPush).toHaveBeenCalledWith("/dynamic_document_dashboard");
  });

  test("publish with empty name_es shows validation error and Swal", async () => {
    const variables = buildVariables();
    variables[0].name_es = "";
    setupStore(pinia, { variables });
    const wrapper = await mountComponent(pinia);

    const publishBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Publicar")
    );
    await publishBtn.trigger("click");
    await flushPromises();

    expect(wrapper.text()).toContain("nombre en pantalla es obligatorio");
    expect(mockSwalFire).toHaveBeenCalledWith(
      expect.objectContaining({ title: "Campos incompletos" })
    );
  });

  test("publish with select field but no options shows validation error", async () => {
    const variables = buildVariables();
    variables[2].select_options = [];
    setupStore(pinia, { variables });
    const wrapper = await mountComponent(pinia);

    const publishBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Publicar")
    );
    await publishBtn.trigger("click");
    await flushPromises();

    expect(wrapper.text()).toContain("al menos una opción");
  });

  test("save as draft skips validation and calls saveDocument", async () => {
    const variables = buildVariables();
    variables[0].name_es = "";
    const { store } = setupStore(pinia, { variables });
    store.documents = [{ id: 1, title: "Test Template", content: "<p>Content</p>", state: "Draft" }];

    const wrapper = await mountComponent(pinia);

    const draftBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Guardar como borrador")
    );
    await draftBtn.trigger("click");

    for (let i = 0; i < 5; i++) {
      await flushPromises();
    }

    expect(store.updateDocument).toHaveBeenCalled();
    expect(mockSwalFire).not.toHaveBeenCalled();
  });

  test("changing summary_field to 'value' auto-adjusts field_type to 'number'", async () => {
    const { store } = setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const summarySelect = wrapper.find("#summary_field_0"); // quality: allow-fragile-selector (stable DOM id)
    await summarySelect.setValue("value");
    await summarySelect.trigger("change");
    await flushPromises();

    expect(store.selectedDocument.variables[0].field_type).toBe("number");
  });

  test("changing summary_field to date classifications auto-adjusts field_type to 'date'", async () => {
    const { store } = setupStore(pinia);
    const wrapper = await mountComponent(pinia);

    const summarySelect = wrapper.find("#summary_field_0"); // quality: allow-fragile-selector (stable DOM id)
    await summarySelect.setValue("start_date");
    await summarySelect.trigger("change");
    await flushPromises();

    expect(store.selectedDocument.variables[0].field_type).toBe("date");
  });

  test("duplicate summary_field classification resets previous variable", async () => {
    const variables = buildVariables();
    variables[0].summary_field = "counterparty";
    const { store } = setupStore(pinia, { variables });
    const wrapper = await mountComponent(pinia);

    const summarySelect1 = wrapper.find("#summary_field_1"); // quality: allow-fragile-selector (stable DOM id)
    await summarySelect1.setValue("counterparty");
    await summarySelect1.trigger("change");
    await flushPromises();

    expect(store.selectedDocument.variables[0].summary_field).toBe("none");
    expect(store.selectedDocument.variables[1].summary_field).toBe("counterparty");
  });
});
