import { mount } from "@vue/test-utils";
import { createPinia, setActivePinia } from "pinia";

import { useDynamicDocumentStore } from "@/stores/dynamic_document";
import { useUserStore } from "@/stores/auth/user";

import DocumentForm from "@/views/dynamic_document/DocumentForm.vue";

const mockShowNotification = jest.fn();
const mockRouterPush = jest.fn();
const mockSwalFire = jest.fn().mockResolvedValue({});

jest.mock("@/shared/notification_message", () => ({
  __esModule: true,
  showNotification: (...args) => mockShowNotification(...args),
}));

jest.mock("@/shared/document_utils", () => ({
  __esModule: true,
  showPreviewModal: { value: false },
  previewDocumentData: { value: null },
}));

jest.mock("sweetalert2", () => ({
  __esModule: true,
  default: { fire: (...args) => mockSwalFire(...args) },
}));

jest.mock("@/stores/services/request_http", () => ({
  __esModule: true,
  create_request: jest.fn(),
}));

jest.mock("@/stores/dashboard/activity_feed", () => ({
  __esModule: true,
  registerUserActivity: jest.fn(),
  ACTION_TYPES: { CREATE: "CREATE", UPDATE: "UPDATE" },
}));

const mockRoute = {
  params: { mode: "creator", id: "1", title: "Test Document" },
};

jest.mock("vue-router", () => ({
  useRoute: () => mockRoute,
  useRouter: () => ({
    push: mockRouterPush,
  }),
}));

jest.mock("@heroicons/vue/24/outline", () => {
  const IconStub = { name: "IconStub", template: "<span />" };
  return { __esModule: true, InformationCircleIcon: IconStub };
});

jest.mock(
  "@/components/dynamic_document/modals/DocumentRelationshipsModal.vue",
  () => ({ __esModule: true, default: { name: "DocumentRelationshipsModal", template: "<div />" } })
);

jest.mock(
  "@/components/dynamic_document/common/DocumentPreviewModal.vue",
  () => ({ __esModule: true, default: { name: "DocumentPreviewModal", template: "<div />" } })
);

const flushPromises = () => new Promise((resolve) => setTimeout(resolve, 0));

function buildVariables() {
  return [
    { name_en: "Name", name_es: "Nombre", field_type: "input", value: "", tooltip: "Enter name" },
    { name_en: "Description", name_es: "Descripción", field_type: "text_area", value: "" },
    { name_en: "Amount", name_es: "Monto", field_type: "number", value: "", currency: "COP" },
    { name_en: "Birth Date", name_es: "Fecha Nacimiento", field_type: "date", value: "" },
    { name_en: "Email", name_es: "Correo", field_type: "email", value: "" },
    {
      name_en: "Category", name_es: "Categoría", field_type: "select", value: "",
      select_options: ["Option A", "Option B", "Option C"],
    },
  ];
}

function setupStores(pinia) {
  const docStore = useDynamicDocumentStore();
  const userStore = useUserStore();

  const mockDoc = {
    id: 1,
    title: "Test Document",
    variables: buildVariables(),
    content: "<p>Template content</p>",
    created_by: 10,
    tags: [],
  };

  jest.spyOn(docStore, "fetchDocumentById").mockResolvedValue(mockDoc);
  jest.spyOn(docStore, "createDocument").mockResolvedValue({ id: 99 });
  jest.spyOn(docStore, "updateDocument").mockResolvedValue({});
  jest.spyOn(docStore, "init").mockResolvedValue();

  userStore.currentUser = { id: 5, first_name: "Test", last_name: "User", email: "t@t.com", role: "client" };
  userStore.users = [];
  jest.spyOn(userStore, "fetchUsers").mockResolvedValue();

  return { docStore, userStore, mockDoc };
}

async function mountComponent(pinia) {
  const wrapper = mount(DocumentForm, {
    global: {
      plugins: [pinia],
      stubs: {
        teleport: true,
      },
    },
  });
  await flushPromises();
  return wrapper;
}

describe("DocumentForm.vue", () => {
  let pinia;

  beforeEach(() => {
    pinia = createPinia();
    setActivePinia(pinia);
    jest.clearAllMocks();
    mockRoute.params = { mode: "creator", id: "1", title: "Test Document" };
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  // quality: disable too_many_assertions (verifying all 6 field types render correctly in a single mount)
  test("renders document title and all field types", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.text()).toContain("Test Document");

    // quality: allow-fragile-selector (stable DOM ids generated by component for each field)
    expect(wrapper.find("#field-0").exists()).toBe(true);
    expect(wrapper.find("#field-0").element.tagName).toBe("INPUT");

    expect(wrapper.find("#field-1").exists()).toBe(true);
    expect(wrapper.find("#field-1").element.tagName).toBe("TEXTAREA");

    expect(wrapper.find("#field-2").exists()).toBe(true);

    expect(wrapper.find("#field-3").exists()).toBe(true);
    expect(wrapper.find("#field-3").attributes("type")).toBe("date");

    expect(wrapper.find("#field-4").exists()).toBe(true);
    expect(wrapper.find("#field-4").attributes("type")).toBe("email");

    expect(wrapper.find("#field-5").exists()).toBe(true);
    expect(wrapper.find("#field-5").element.tagName).toBe("SELECT");
  });

  test("renders tooltip icon when variable has tooltip", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const tooltipIcons = wrapper.findAllComponents({ name: "IconStub" });
    const hasTooltipIcons = tooltipIcons.length >= 1;
    expect(hasTooltipIcons).toBe(true);
  });

  test("currency prefix renders for number field with currency", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.text()).toContain("COP");
  });

  test("select field renders all options", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const select = wrapper.find("#field-5"); // quality: allow-fragile-selector (stable DOM id)
    const options = select.findAll("option");
    expect(options.length).toBe(4);
    expect(options[0].text()).toContain("Seleccione una opción");
    expect(options[1].text()).toBe("Option A");
    expect(options[2].text()).toBe("Option B");
    expect(options[3].text()).toBe("Option C");
  });

  test("complete/generate button is disabled when fields are empty", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const generateBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Generar")
    );
    expect(generateBtn).toBeTruthy();
    expect(generateBtn.attributes("disabled")).toBeDefined();
  });

  test("complete/generate button becomes enabled when all fields are filled", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    // quality: allow-fragile-selector (stable DOM ids generated by component for each field)
    await wrapper.find("#field-0").setValue("John Doe");
    await wrapper.find("#field-1").setValue("A description");
    await wrapper.find("#field-2").setValue("5000");
    await wrapper.find("#field-3").setValue("2025-01-01");
    await wrapper.find("#field-4").setValue("john@test.com");
    await wrapper.find("#field-5").setValue("Option A");
    await flushPromises();

    const generateBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Generar")
    );
    expect(generateBtn.attributes("disabled")).toBeUndefined();
  });

  test("save progress button visible in creator mode", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const saveBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Guardar progreso")
    );
    expect(saveBtn).toBeTruthy();
  });

  test("cancel button navigates back to dashboard", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const cancelBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Cancelar")
    );
    expect(cancelBtn).toBeTruthy();

    await cancelBtn.trigger("click");
    await flushPromises();

    expect(mockRouterPush).toHaveBeenCalledWith("/dynamic_document_dashboard");
  });

  test("validation error appears for invalid email", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const emailField = wrapper.find("#field-4"); // quality: allow-fragile-selector (stable DOM id)
    await emailField.setValue("not-an-email");
    await emailField.trigger("input");
    await flushPromises();

    expect(wrapper.text()).toContain("correo electrónico válido");
  });

  test("validation error appears for invalid number", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const numberField = wrapper.find("#field-2"); // quality: allow-fragile-selector (stable DOM id)
    await numberField.setValue("abc");
    await numberField.trigger("input");
    await flushPromises();

    expect(wrapper.text()).toContain("número válido");
  });

  test("shows loading state while document is being fetched", async () => {
    const docStore = useDynamicDocumentStore();
    jest.spyOn(docStore, "fetchDocumentById").mockReturnValue(new Promise(() => {}));
    const userStore = useUserStore();
    userStore.currentUser = { id: 5 };
    jest.spyOn(userStore, "fetchUsers").mockResolvedValue();

    const wrapper = mount(DocumentForm, {
      global: {
        plugins: [pinia],
        stubs: { teleport: true },
      },
    });

    expect(wrapper.text()).toContain("Cargando documento");
  });

  test("editor mode shows 'Guardar cambios como Borrador' button", async () => {
    mockRoute.params = { mode: "editor", id: "1", title: "Edit Doc" };
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    const saveBtn = wrapper.findAll("button").find(
      (b) => b.text().includes("Guardar cambios como Borrador")
    );
    expect(saveBtn).toBeTruthy();
  });

  test("textarea field spans full width (col-span-3)", async () => {
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    // quality: allow-fragile-selector (stable DOM id)
    const textareaContainer = wrapper.find("#field-1").element.closest("[class*='col-span']");
    expect(textareaContainer.classList.contains("lg:col-span-3")).toBe(true);
  });

  test("formalize mode renders signer search section", async () => {
    mockRoute.params = { mode: "formalize", id: "1", title: "Sign Doc" };
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.text()).toContain("Seleccionar usuarios que deben firmar");
  });

  test("formalize mode shows Formalizar y Agregar Firmas button text", async () => {
    mockRoute.params = { mode: "formalize", id: "1", title: "Sign Doc" };
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.text()).toContain("Formalizar y Agregar Firmas");
  });

  test("formalize button remains disabled when no signers are selected and all fields filled", async () => {
    mockRoute.params = { mode: "formalize", id: "1", title: "Sign Doc" };
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    // Fill all required fields
    // quality: allow-fragile-selector (dynamic form field IDs are stable within this mock fixture)
    await wrapper.find("#field-0").setValue("John Doe");
    await wrapper.find("#field-1").setValue("A description");
    await wrapper.find("#field-2").setValue("5000");
    await wrapper.find("#field-3").setValue("2025-01-01");
    await wrapper.find("#field-4").setValue("john@test.com");
    await wrapper.find("#field-5").setValue("Option A");
    await flushPromises();

    const formalizeBtn = wrapper.findAll("button").find((b) =>
      b.text().includes("Formalizar")
    );
    expect(formalizeBtn.attributes("disabled")).toBeDefined();
  });

  test("correction mode shows Guardar y reenviar para firma button text", async () => {
    mockRoute.params = { mode: "correction", id: "1", title: "Correction Doc" };
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.text()).toContain("Guardar y reenviar para firma");
  });

  test("correction mode renders the signature due date input", async () => {
    mockRoute.params = { mode: "correction", id: "1", title: "Correction Doc" };
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.text()).toContain("Fecha límite para firmar");
    expect(wrapper.find('[data-testid="correction-signature-due-date"]').exists()).toBe(true);
  });

  test("editor mode does not render the correction due date input", async () => {
    mockRoute.params = { mode: "editor", id: "1", title: "Edit Doc" };
    setupStores(pinia);
    const wrapper = await mountComponent(pinia);

    expect(wrapper.find('[data-testid="correction-signature-due-date"]').exists()).toBe(false);
  });

  test("correction mode prefills a future signature due date", async () => {
    mockRoute.params = { mode: "correction", id: "1", title: "Correction Doc" };
    const { docStore, mockDoc } = setupStores(pinia);
    const futureDate = new Date(Date.now() + 10 * 86400000).toISOString().split("T")[0];
    docStore.fetchDocumentById.mockResolvedValue({ ...mockDoc, signature_due_date: futureDate });

    const wrapper = await mountComponent(pinia);

    expect(wrapper.find('[data-testid="correction-signature-due-date"]').element.value).toBe(futureDate);
  });

  test("correction mode leaves the due date empty when the stored date is past", async () => {
    mockRoute.params = { mode: "correction", id: "1", title: "Correction Doc" };
    const { docStore, mockDoc } = setupStores(pinia);
    docStore.fetchDocumentById.mockResolvedValue({ ...mockDoc, signature_due_date: "2020-01-01" });

    const wrapper = await mountComponent(pinia);

    expect(wrapper.find('[data-testid="correction-signature-due-date"]').element.value).toBe("");
  });

  test("correction save sends the chosen signature due date", async () => {
    mockRoute.params = { mode: "correction", id: "1", title: "Correction Doc" };
    const { docStore } = setupStores(pinia);
    const correctSpy = jest.spyOn(docStore, "correctDocument").mockResolvedValue({ id: 1 });
    const wrapper = await mountComponent(pinia);

    // quality: allow-fragile-selector (stable DOM ids generated by component for each field)
    await wrapper.find("#field-0").setValue("John Doe");
    await wrapper.find("#field-1").setValue("A description");
    await wrapper.find("#field-2").setValue("5000");
    await wrapper.find("#field-3").setValue("2025-01-01");
    await wrapper.find("#field-4").setValue("john@test.com");
    await wrapper.find("#field-5").setValue("Option A");
    const futureDate = new Date(Date.now() + 10 * 86400000).toISOString().split("T")[0];
    await wrapper.find('[data-testid="correction-signature-due-date"]').setValue(futureDate);
    await flushPromises();

    const saveBtn = wrapper.findAll("button").find((b) => b.text().includes("Guardar y reenviar para firma"));
    await saveBtn.trigger("click");
    await flushPromises();

    expect(correctSpy).toHaveBeenCalledWith(1, expect.objectContaining({ signature_due_date: futureDate }));
  });

  test("correction save clears the due date when the input is left empty", async () => {
    mockRoute.params = { mode: "correction", id: "1", title: "Correction Doc" };
    const { docStore, mockDoc } = setupStores(pinia);
    docStore.fetchDocumentById.mockResolvedValue({ ...mockDoc, signature_due_date: "2020-01-01" });
    const correctSpy = jest.spyOn(docStore, "correctDocument").mockResolvedValue({ id: 1 });
    const wrapper = await mountComponent(pinia);

    // quality: allow-fragile-selector (stable DOM ids generated by component for each field)
    await wrapper.find("#field-0").setValue("John Doe");
    await wrapper.find("#field-1").setValue("A description");
    await wrapper.find("#field-2").setValue("5000");
    await wrapper.find("#field-3").setValue("2025-01-01");
    await wrapper.find("#field-4").setValue("john@test.com");
    await wrapper.find("#field-5").setValue("Option A");
    await flushPromises();

    const saveBtn = wrapper.findAll("button").find((b) => b.text().includes("Guardar y reenviar para firma"));
    await saveBtn.trigger("click");
    await flushPromises();

    expect(correctSpy).toHaveBeenCalledWith(1, expect.objectContaining({ signature_due_date: "" }));
  });
});
