# Generated by Django 5.0.6 on 2024-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='Hipervínculo')),
            ],
            options={
                'verbose_name': 'Enlace Legal',
                'verbose_name_plural': 'Enlaces Legales',
            },
        ),
        migrations.DeleteModel(
            name='LegalUserLink',
        ),
    ]
