# Generated by Django 5.0.6 on 2024-12-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_legallink_delete_legaluserlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legallink',
            options={'verbose_name': 'Legal Link', 'verbose_name_plural': 'Legal Links'},
        ),
    ]
