# Generated by Django 5.0.6 on 2024-12-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_remove_user_marital_status_user_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('NUIP', 'NUIP'), ('NIT', 'NIT'), ('EIN', 'EIN')], help_text='The type of identification document.', max_length=10, null=True),
        ),
    ]
