# Generated by Django 5.0.6 on 2025-02-07 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_alter_user_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the dynamic document.', max_length=200)),
                ('content', models.TextField(help_text='Content of the document.')),
                ('state', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Progress', 'Progress'), ('Completed', 'Completed')], default='Draft', help_text='State of the document.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Document creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Document last updated timestamp.')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The user to whom the document is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='The user who created the document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, help_text='Variable name in English.', max_length=100, null=True)),
                ('name_es', models.CharField(blank=True, help_text='Display name in Spanish.', max_length=100, null=True)),
                ('tooltip', models.CharField(blank=True, help_text='Display a tooltip message.', max_length=200, null=True)),
                ('field_type', models.CharField(choices=[('input', 'Input'), ('text_area', 'Text Area')], default='input', help_text='Field type for the variable.', max_length=20)),
                ('value', models.TextField(blank=True, help_text='Value filled by the user.', null=True)),
                ('document', models.ForeignKey(help_text='The dynamic document this variable belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='gym_app.dynamicdocument')),
            ],
        ),
    ]
