# Generated by Django 5.0.6 on 2025-01-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_alter_user_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the dynamic document.', max_length=200)),
                ('content', models.TextField(help_text='Content of the document.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variables used in the document.')),
                ('values', models.JSONField(blank=True, default=dict, help_text='Values of the variables.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Document creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Document last updated timestamp.')),
            ],
        ),
    ]
