# Generated by Django 5.0.6 on 2025-01-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_alter_user_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the dynamic document.', max_length=200)),
                ('content', models.TextField(help_text='Content of the document.')),
                ('variables_en', models.JSONField(blank=True, default=list, help_text='List of variables (in English) used in the document.')),
                ('variables_es', models.JSONField(blank=True, default=list, help_text='List of variables (in Spanish) used in the document.')),
                ('values', models.JSONField(blank=True, default=dict, help_text='Values of the variables.')),
                ('field_type', models.CharField(choices=[('input', 'Input'), ('text_area', 'Text Area')], default='input', help_text='Field type for the document (input or text_area).', max_length=20)),
                ('state', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Progress', 'Progress'), ('Completed', 'Completed')], default='Draft', help_text='State of the document.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Document creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Document last updated timestamp.')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The user to whom the document is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='The user who created the document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
