# Generated by Django 5.0.6 on 2025-04-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_legaldocument_delete_legallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='legal_updates/')),
                ('link_text', models.CharField(max_length=100)),
                ('link_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actualización Legal',
                'verbose_name_plural': 'Actualizaciones Legales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'verbose_name': 'Legal Document', 'verbose_name_plural': 'Legal Documents'},
        ),
    ]
