# Generated by Django 5.0.6 on 2025-04-08 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0009_legalupdate_alter_legaldocument_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalupdate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legal Update', 'verbose_name_plural': 'Legal Updates'},
        ),
        migrations.CreateModel(
            name='RecentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.process')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_viewed'],
                'unique_together': {('user', 'process')},
            },
        ),
    ]
