# Generated by Django 5.0.6 on 2025-04-08 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0010_alter_legalupdate_options_recentprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.dynamicdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_visited'],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
