# Generated by Django 5.0.6 on 2025-05-14 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0012_activityfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(help_text='The image of the electronic signature.', upload_to='signatures/')),
                ('method', models.CharField(choices=[('upload', 'Upload'), ('draw', 'Draw')], help_text='Method used to create the signature.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the signature was created.')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which the signature was submitted.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
