# Generated by Django 5.0.6 on 2025-05-22 16:05
"""
Migration to add digital signature capabilities to dynamic documents.

This migration:
1. Adds a 'requires_signature' field to the DynamicDocument model to flag documents that need signatures
2. Creates a new DocumentSignature model to track signatures for documents, their status, and metadata
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0013_usersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='requires_signature',
            field=models.BooleanField(default=False, help_text='Indicates if this document requires signatures.'),
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed', models.BooleanField(default=False, help_text='Whether the document has been signed by this user')),
                ('signed_at', models.DateTimeField(blank=True, help_text='When the document was signed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the signature was submitted', null=True)),
                ('signature_position', models.PositiveIntegerField(default=0, help_text='Position in the signing sequence (0 means no specific order)')),
                ('document', models.ForeignKey(help_text='The document that requires signature', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='gym_app.dynamicdocument')),
                ('signer', models.ForeignKey(help_text='The user who needs to sign the document', on_delete=django.db.models.deletion.CASCADE, related_name='pending_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signature_position', 'signer__email'],
                'unique_together': {('document', 'signer')},
            },
        ),
    ]
