# Generated by Django 5.0.6 on 2025-05-22 16:19
"""
Migration to enhance digital signature functionality with document versioning.

This migration:
1. Adds a 'fully_signed' field to the DynamicDocument model to track when all signatures are complete
2. Updates the DynamicDocument state choices to include 'FullySigned' status
3. Creates a DocumentVersion model to store different versions of documents (original and signed versions)
"""

import django.db.models.deletion
import gym_app.models.dynamic_document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0014_dynamicdocument_requires_signature_documentsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='fully_signed',
            field=models.BooleanField(default=False, help_text='Indicates if the document has been signed by all required signers.'),
        ),
        migrations.AlterField(
            model_name='dynamicdocument',
            name='state',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Progress', 'Progress'), ('Completed', 'Completed'), ('PendingSignatures', 'Pending Signatures'), ('FullySigned', 'Fully Signed')], default='Draft', help_text='State of the document.', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('original', 'Original Document'), ('signed', 'Signed Version')], default='original', help_text='Type of document version', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('file', models.FileField(help_text='The document file in PDF or Word format', upload_to=gym_app.models.dynamic_document.document_version_path)),
                ('content_type', models.CharField(help_text='The MIME type of the file', max_length=100)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Version number, incremented with each signature')),
                ('document', models.ForeignKey(help_text='The document this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gym_app.dynamicdocument')),
                ('signed_by', models.ForeignKey(blank=True, help_text='The user who added their signature in this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_document_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('document', 'version_number', 'version_type')},
            },
        ),
    ]
