# Generated by Django 5.0.6 on 2025-05-27 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0015_dynamicdocument_fully_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentdocument',
            name='document',
            field=models.ForeignKey(help_text='The document that was viewed.', on_delete=django.db.models.deletion.CASCADE, to='gym_app.dynamicdocument'),
        ),
        migrations.AlterField(
            model_name='recentdocument',
            name='last_visited',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of when the document was last viewed.'),
        ),
        migrations.AlterField(
            model_name='recentdocument',
            name='user',
            field=models.ForeignKey(help_text='The user who viewed the document.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
