# Generated by Django 5.0.6 on 2025-05-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0016_alter_recentdocument_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the signature was last updated.'),
        ),
    ]
