# Generated by Django 5.0.6 on 2025-05-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0017_usersignature_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsignature',
            options={'ordering': ['signer__email']},
        ),
        migrations.RemoveField(
            model_name='documentsignature',
            name='signature_position',
        ),
    ]
