# Generated by Django 5.0.6 on 2025-05-28 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0018_alter_documentsignature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignature',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the signature record was created'),
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
