# Generated by Django 5.0.6 on 2025-05-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0019_remove_usersignature_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which the signature was submitted.', null=True),
        ),
    ]
