# Generated by Django 5.0.6 on 2025-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0020_alter_usersignature_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer'), ('corporate_client', 'Corporate Client'), ('basic', 'Basic')], default='client', help_text="The role of the user within the system (default: 'client').", max_length=20),
        ),
    ]
