# Generated by Django 5.0.6 on 2025-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0021_alter_legaldocument_file_alter_legaldocument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvariable',
            name='field_type',
            field=models.CharField(choices=[('input', 'Input'), ('text_area', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email')], default='input', help_text='Field type for the variable.', max_length=20),
        ),
    ]
