# Generated by Django 5.0.6 on 2025-06-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0022_alter_documentvariable_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvariable',
            name='select_options',
            field=models.JSONField(blank=True, help_text='Options for select type fields.', null=True),
        ),
        migrations.AlterField(
            model_name='documentvariable',
            name='field_type',
            field=models.CharField(choices=[('input', 'Input'), ('text_area', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('select', 'Select')], default='input', help_text='Field type for the variable.', max_length=20),
        ),
    ]
