# Generated by Django 5.0.6 on 2025-07-28 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0024_documentfolder_tag_dynamicdocument_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, all users can view and use this document without explicit permissions.'),
        ),
        migrations.CreateModel(
            name='DocumentUsabilityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read_only', 'Read Only'), ('edit', 'Edit'), ('full_access', 'Full Access')], default='read_only', help_text='Level of access the user has', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When this permission was granted')),
                ('document', models.ForeignKey(help_text='The document this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='usability_permissions', to='gym_app.dynamicdocument')),
                ('granted_by', models.ForeignKey(help_text='The lawyer who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_usability_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who can use the document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Usability Permission',
                'verbose_name_plural': 'Document Usability Permissions',
                'ordering': ['-granted_at'],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVisibilityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When this permission was granted')),
                ('document', models.ForeignKey(help_text='The document this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='visibility_permissions', to='gym_app.dynamicdocument')),
                ('granted_by', models.ForeignKey(help_text='The lawyer who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_visibility_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who can view the document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Visibility Permission',
                'verbose_name_plural': 'Document Visibility Permissions',
                'ordering': ['-granted_at'],
                'unique_together': {('document', 'user')},
            },
        ),
    ]
