# Generated by Django 5.0.6 on 2025-07-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0025_dynamicdocument_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentusabilitypermission',
            name='permission_type',
        ),
    ]
