# Generated by Django 5.0.6 on 2025-07-29 23:54

import gym_app.models.dynamic_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0026_remove_documentusabilitypermission_permission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='letterhead_image',
            field=models.ImageField(blank=True, help_text='Imagen PNG para membrete que se mostrará como fondo centrado en cada página del documento. Recomendado: 612x792 píxeles para tamaño oficio.', null=True, upload_to=gym_app.models.dynamic_document.letterhead_image_path),
        ),
    ]
