# Generated by Django 5.0.6 on 2025-09-04 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0027_dynamicdocument_letterhead_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrequest',
            name='request_number',
            field=models.CharField(blank=True, help_text='Unique identifier for the legal request (e.g., SOL-2024-001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='legalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('RESPONDED', 'Respondida'), ('CLOSED', 'Cerrada')], default='PENDING', help_text='Current status of the legal request', max_length=20),
        ),
        migrations.AddField(
            model_name='legalrequest',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the status was last updated'),
        ),
        migrations.CreateModel(
            name='LegalRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text='The response message content')),
                ('user_type', models.CharField(choices=[('lawyer', 'Abogado'), ('client', 'Cliente')], help_text='Type of user who created the response', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the response was created')),
                ('legal_request', models.ForeignKey(help_text='The legal request this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='gym_app.legalrequest')),
                ('user', models.ForeignKey(help_text='The user who created this response', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
