# Generated by Django 5.0.6 on 2025-09-04 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0028_add_legal_request_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrequest',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this legal request', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
