# Generated by Django 5.0.6 on 2025-09-04 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0031_populate_user_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='legalrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='legalrequest',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='legalrequest',
            name='user',
            field=models.ForeignKey(default=84, help_text='The user who created this legal request', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
