# Generated by Django 5.0.6 on 2025-09-06 22:04

import gym_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0032_remove_duplicate_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='letterhead_image',
            field=models.ImageField(blank=True, help_text='Imagen PNG para membrete global que se aplicará a todos los documentos del usuario cuando no tengan uno específico. Recomendado: 612x792 píxeles.', null=True, upload_to=gym_app.models.user.user_letterhead_image_path),
        ),
    ]
