# Generated by Django 5.0.6 on 2025-09-08 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0033_user_letterhead_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the relationship was created.')),
                ('created_by', models.ForeignKey(help_text='User who created this relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='created_document_relationships', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(help_text='The document from which the relationship is created.', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_source', to='gym_app.dynamicdocument')),
                ('target_document', models.ForeignKey(help_text='The document that is being related to the source document.', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_target', to='gym_app.dynamicdocument')),
            ],
            options={
                'verbose_name': 'Document Relationship',
                'verbose_name_plural': 'Document Relationships',
                'ordering': ['-created_at'],
                'unique_together': {('source_document', 'target_document')},
            },
        ),
    ]
