# Generated by Django 5.0.6 on 2025-09-22 16:34

import django.db.models.deletion
import gym_app.models.organization
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0035_corporaterequestfiles_corporaterequesttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporaterequest',
            name='corporate_client',
            field=models.ForeignKey(help_text='The corporate client who will handle this request (should be organization leader)', limit_choices_to={'role': 'corporate_client'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_corporate_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título/nombre de la organización', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada de la organización')),
                ('profile_image', models.ImageField(blank=True, help_text='Imagen de perfil de la organización', null=True, upload_to=gym_app.models.organization.organization_profile_image_path)),
                ('cover_image', models.ImageField(blank=True, help_text='Imagen de portada de la organización', null=True, upload_to=gym_app.models.organization.organization_cover_image_path)),
                ('is_active', models.BooleanField(default=True, help_text='Si la organización está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la organización')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('corporate_client', models.ForeignKey(help_text='Cliente corporativo líder de la organización', limit_choices_to={'role': 'corporate_client'}, on_delete=django.db.models.deletion.CASCADE, related_name='led_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='corporaterequest',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization through which this request is made', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_requests', to='gym_app.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para la invitación', unique=True)),
                ('message', models.TextField(blank=True, help_text='Mensaje personalizado de invitación', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada')], default='PENDING', help_text='Estado de la invitación', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de envío de la invitación')),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración de la invitación')),
                ('responded_at', models.DateTimeField(blank=True, help_text='Fecha de respuesta a la invitación', null=True)),
                ('invited_by', models.ForeignKey(help_text='Cliente corporativo que envió la invitación', limit_choices_to={'role': 'corporate_client'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(help_text='Usuario invitado (cliente normal)', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organización a la que se invita', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gym_app.organization')),
            ],
            options={
                'verbose_name': 'Invitación de Organización',
                'verbose_name_plural': 'Invitaciones de Organización',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'invited_user', 'status')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Líder'), ('ADMIN', 'Administrador'), ('MEMBER', 'Miembro')], default='MEMBER', help_text='Rol del usuario en la organización', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de unión a la organización')),
                ('is_active', models.BooleanField(default=True, help_text='Si la membresía está activa')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Fecha de desactivación de la membresía', null=True)),
                ('organization', models.ForeignKey(help_text='Organización', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gym_app.organization')),
                ('user', models.ForeignKey(help_text='Usuario miembro', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de Organización',
                'verbose_name_plural': 'Membresías de Organización',
                'ordering': ['-joined_at'],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
