# Generated by Django 5.0.6 on 2025-09-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0036_alter_corporaterequest_corporate_client_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del post', max_length=200)),
                ('content', models.TextField(help_text='Contenido del post')),
                ('link_name', models.CharField(blank=True, help_text='Nombre del hipervínculo (opcional)', max_length=100, null=True)),
                ('link_url', models.URLField(blank=True, help_text='URL del hipervínculo (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si el post está activo/visible')),
                ('is_pinned', models.BooleanField(default=False, help_text='Si el post está fijado en la parte superior')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del post')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('author', models.ForeignKey(help_text='Cliente corporativo que creó el post', limit_choices_to={'role': 'corporate_client'}, on_delete=django.db.models.deletion.CASCADE, related_name='authored_organization_posts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organización a la que pertenece el post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gym_app.organization')),
            ],
            options={
                'verbose_name': 'Post de Organización',
                'verbose_name_plural': 'Posts de Organización',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
