# Generated by Django 5.0.6 on 2025-10-16 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0037_organizationpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='invited_user',
            field=models.ForeignKey(help_text='Usuario invitado (cliente normal o básico)', limit_choices_to={'role__in': ['client', 'basic']}, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
