# Generated by Django 5.0.6 on 2025-11-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0038_alter_organizationinvitation_invited_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntranetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the intranet documents section', null=True, upload_to='intranet/covers/', verbose_name='Cover Image')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image for the intranet documents section', null=True, upload_to='intranet/profiles/', verbose_name='Profile Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intranet Profile',
                'verbose_name_plural': 'Intranet Profiles',
            },
        ),
    ]
