# Generated by Django 5.0.6 on 2025-11-25 22:05

import gym_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0039_intranetprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='letterhead_word_template',
            field=models.FileField(blank=True, help_text='Plantilla Word (.docx) para membrete global utilizada al generar documentos Word.', null=True, upload_to=gym_app.models.user.user_letterhead_template_path),
        ),
    ]
