# Generated by Django 5.0.6 on 2025-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0040_user_letterhead_word_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfeed',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('finish', 'Finish'), ('delete', 'Delete'), ('update', 'Update'), ('download', 'Download'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
