# Generated by Django 5.0.6 on 2025-11-28 05:50

import gym_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0041_alter_activityfeed_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='letterhead_image',
            field=models.ImageField(blank=True, help_text='Imagen PNG para membrete global que se aplicará a todos los documentos del usuario cuando no tengan uno específico. Recomendado: 2550x3300 píxeles (tamaño carta, aproximadamente 8.5 x 11 pulgadas a 300 DPI).', null=True, upload_to=gym_app.models.user.user_letterhead_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('lawyer', 'Lawyer'), ('corporate_client', 'Corporate Client'), ('basic', 'Basic')], default='basic', help_text="The role of the user within the system (default: 'basic').", max_length=20),
        ),
    ]
