# Generated by Django 5.0.6 on 2025-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0042_alter_user_letterhead_image_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvariable',
            name='currency',
            field=models.CharField(blank=True, choices=[('COP', 'COP'), ('USD', 'USD'), ('EUR', 'EUR')], help_text='Moneda asociada al valor cuando la variable está clasificada como Valor.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='documentvariable',
            name='summary_field',
            field=models.CharField(choices=[('none', 'Sin clasificar'), ('counterparty', 'Usuario / Contraparte'), ('object', 'Objeto'), ('value', 'Valor'), ('term', 'Plazo'), ('subscription_date', 'Fecha de suscripción'), ('start_date', 'Fecha de inicio'), ('end_date', 'Fecha de fin')], default='none', help_text='Clasificación opcional para usar este campo en columnas resumen de las tablas.', max_length=30),
        ),
    ]
