# Generated by Django 5.0.6 on 2025-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0043_documentvariable_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignature',
            name='rejected',
            field=models.BooleanField(default=False, help_text='Whether this signer rejected the document instead of signing'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the signer rejected the document', null=True),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='rejection_comment',
            field=models.TextField(blank=True, help_text='Optional comment explaining the rejection', null=True),
        ),
        migrations.AddField(
            model_name='dynamicdocument',
            name='signature_due_date',
            field=models.DateField(blank=True, help_text='Optional deadline date for collecting all required signatures.', null=True),
        ),
        migrations.AlterField(
            model_name='dynamicdocument',
            name='state',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Progress', 'Progress'), ('Completed', 'Completed'), ('PendingSignatures', 'Pending Signatures'), ('FullySigned', 'Fully Signed'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Draft', help_text='State of the document.', max_length=20),
        ),
    ]
