# Generated by Django 5.0.6 on 2025-12-10 02:02

import gym_app.models.dynamic_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0045_stage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='letterhead_word_template',
            field=models.FileField(blank=True, help_text='Plantilla Word (.docx) para membrete específica de este documento, utilizada al generar documentos Word cuando está configurada.', null=True, upload_to=gym_app.models.dynamic_document.document_letterhead_template_path),
        ),
    ]
