# Generated by Django 5.0.6 on 2025-12-12 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0046_dynamicdocument_letterhead_word_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='The process completion percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
