# Generated by Django 5.0.6 on 2025-12-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0047_process_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='authority_email',
            field=models.EmailField(blank=True, help_text='Email address of the authority handling the case.', max_length=254, null=True),
        ),
    ]
