# Generated by Django 5.0.6 on 2025-12-19 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0049_process_clients_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basico', 'Básico'), ('cliente', 'Cliente'), ('corporativo', 'Corporativo')], help_text='The type of subscription plan.', max_length=20)),
                ('payment_source_id', models.CharField(help_text='Wompi payment source token for recurring payments.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', help_text='Current status of the subscription.', max_length=20)),
                ('next_billing_date', models.DateField(help_text='The date when the next billing will occur.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The subscription amount in COP.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the subscription was last updated.')),
                ('user', models.ForeignKey(help_text='The user who owns this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
