# Generated by Django 5.0.6 on 2025-12-19 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0050_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The payment amount in COP.', max_digits=10)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('pending', 'Pending'), ('error', 'Error')], help_text='Payment status.', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Wompi transaction ID.', max_length=255, null=True)),
                ('reference', models.CharField(help_text='Payment reference.', max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='When the payment was processed.')),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed.', null=True)),
                ('subscription', models.ForeignKey(help_text='The subscription this payment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gym_app.subscription')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-payment_date'],
            },
        ),
    ]
