# Generated by Django 5.0.6 on 2025-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0051_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_source_id',
            field=models.CharField(blank=True, help_text='Wompi payment source token for recurring payments.', max_length=255, null=True),
        ),
    ]
