# Generated by Django 5.0.6 on 2026-03-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0053_create_email_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'secop_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SECOPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alert name for reference', max_length=200)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords to search in description')),
                ('entities', models.TextField(blank=True, help_text='Comma-separated entity names')),
                ('departments', models.TextField(blank=True, help_text='Comma-separated department names')),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('procurement_methods', models.TextField(blank=True, help_text='Comma-separated procurement modalities')),
                ('frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Summary')], default='DAILY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secop_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SECOP Alert',
                'verbose_name_plural': 'SECOP Alerts',
                'db_table': 'secop_alert',
            },
        ),
        migrations.CreateModel(
            name='SECOPProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(db_index=True, help_text='Unique process ID from SECOP (e.g., CO1.REQ.3908932)', max_length=100, unique=True)),
                ('reference', models.CharField(blank=True, help_text='Process reference number', max_length=200)),
                ('entity_name', models.CharField(help_text='Contracting entity name', max_length=500)),
                ('entity_nit', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('entity_level', models.CharField(blank=True, help_text='Entity level: Nacional, Territorial', max_length=50)),
                ('procedure_name', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, help_text='Full process description/object')),
                ('phase', models.CharField(blank=True, help_text='Current phase', max_length=100)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50)),
                ('procurement_method', models.CharField(blank=True, max_length=200)),
                ('procurement_justification', models.CharField(blank=True, max_length=500)),
                ('contract_type', models.CharField(blank=True, max_length=200)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price in COP', max_digits=20, null=True)),
                ('duration_value', models.IntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, help_text='Deadline for proposal submission', null=True)),
                ('process_url', models.URLField(blank=True, max_length=500)),
                ('unspsc_code', models.CharField(blank=True, max_length=100)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw JSON from API for fields not explicitly mapped', null=True)),
            ],
            options={
                'verbose_name': 'SECOP Process',
                'verbose_name_plural': 'SECOP Processes',
                'db_table': 'secop_process',
                'indexes': [models.Index(fields=['status'], name='secop_proce_status_335bb6_idx'), models.Index(fields=['closing_date'], name='secop_proce_closing_bc5c8d_idx'), models.Index(fields=['department'], name='secop_proce_departm_0b6e00_idx'), models.Index(fields=['procurement_method'], name='secop_proce_procure_eb2bde_idx'), models.Index(fields=['base_price'], name='secop_proce_base_pr_d7004a_idx'), models.Index(fields=['publication_date'], name='secop_proce_publica_8b7d08_idx'), models.Index(fields=['entity_name'], name='secop_proce_entity__efe9d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('filters', models.JSONField(help_text='Stored filter parameters as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secop_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secop_saved_view',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProcessClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERESTING', 'Interesting'), ('UNDER_REVIEW', 'Under Review'), ('DISCARDED', 'Discarded'), ('APPLIED', 'Applied')], default='INTERESTING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for the team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secop_classifications', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='gym_app.secopprocess')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'db_table': 'secop_classification',
                'unique_together': {('process', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gym_app.secopalert')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to='gym_app.secopprocess')),
            ],
            options={
                'db_table': 'secop_alert_notification',
                'unique_together': {('alert', 'process')},
            },
        ),
    ]
