# Generated by Django 5.0.6 on 2026-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0054_synclog_secopalert_secopprocess_savedview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text="If true, this view's filters are applied by default when entering the module"),
        ),
    ]
