# Generated by Django 5.0.6 on 2026-03-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0055_add_is_favorite_to_savedview'),
    ]

    operations = [
        migrations.AddField(
            model_name='secopalert',
            name='unspsc_code',
            field=models.TextField(blank=True, help_text='Comma-separated UNSPSC codes'),
        ),
    ]
