# Generated by Django 5.0.6 on 2026-04-08 17:40

import django.db.models.deletion
import gym_app.models.service_tramite
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0056_add_unspsc_code_to_secop_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('field_type', models.CharField(choices=[('input', 'Texto corto'), ('text_area', 'Texto largo'), ('number', 'Numero'), ('date', 'Fecha'), ('email', 'Correo electronico'), ('select_single', 'Seleccion unica'), ('select_multiple', 'Seleccion multiple'), ('file', 'Archivo')], default='input', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('options', models.JSONField(blank=True, null=True)),
                ('allowed_extensions', models.JSONField(blank=True, null=True)),
                ('allow_multiple_files', models.BooleanField(default=False)),
                ('max_files', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('lawyer', 'Lawyer'), ('corporate_client', 'Corporate Client'), ('basic', 'Basic')], default='basic', help_text="The role of the user within the system (default: 'basic').", max_length=20),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('short_title', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to=gym_app.models.service_tramite._service_icon_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'featured_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Abierto'), ('IN_STUDY', 'En Estudio'), ('IN_PROGRESS', 'En Tramite'), ('ANSWERED', 'Contestado'), ('FINALIZED', 'Finalizado')], default='DRAFT', max_length=20)),
                ('tracking_year', models.PositiveIntegerField(blank=True, null=True)),
                ('tracking_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('current_stage', models.PositiveIntegerField(default=1)),
                ('legal_note', models.CharField(default='Esta solicitud esta sujeta a estudio y revision por parte del abogado asignado', max_length=255)),
                ('generated_document', models.FileField(blank=True, null=True, upload_to=gym_app.models.service_tramite._request_document_path)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='gym_app.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(max_length=80)),
                ('field_label', models.CharField(max_length=160)),
                ('field_type', models.CharField(max_length=20)),
                ('stage_title', models.CharField(max_length=140)),
                ('stage_order', models.PositiveIntegerField(default=1)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_answers', to='gym_app.servicefield')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gym_app.servicerequest')),
            ],
            options={
                'ordering': ['stage_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestFieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=gym_app.models.service_tramite._request_field_file_path)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_files', to='gym_app.servicefield')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_files', to='gym_app.servicerequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestLawyerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status_before', models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Abierto'), ('IN_STUDY', 'En Estudio'), ('IN_PROGRESS', 'En Tramite'), ('ANSWERED', 'Contestado'), ('FINALIZED', 'Finalizado')], max_length=20)),
                ('status_after', models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Abierto'), ('IN_STUDY', 'En Estudio'), ('IN_PROGRESS', 'En Tramite'), ('ANSWERED', 'Contestado'), ('FINALIZED', 'Finalizado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_responses', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_responses', to='gym_app.servicerequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestLawyerResponseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=gym_app.models.service_tramite._request_response_file_path)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gym_app.servicerequestlawyerresponse')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='gym_app.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='servicefield',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='gym_app.servicestage'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('tracking_sequence__isnull', False), ('tracking_year__isnull', False)), fields=('tracking_year', 'tracking_sequence'), name='unique_service_request_year_sequence'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestanswer',
            constraint=models.UniqueConstraint(fields=('service_request', 'field_key'), name='unique_answer_by_request_and_field_key'),
        ),
        migrations.AddConstraint(
            model_name='servicestage',
            constraint=models.UniqueConstraint(fields=('service', 'order'), name='unique_service_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='servicefield',
            constraint=models.UniqueConstraint(fields=('stage', 'key'), name='unique_service_field_key_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='servicefield',
            constraint=models.UniqueConstraint(fields=('stage', 'order'), name='unique_service_field_order_per_stage'),
        ),
    ]
