# Generated by Django 5.0.6 on 2026-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0058_seed_registro_marcario_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='signature_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('issuer_only', 'Issuer Only'), ('informative', 'Informative')], default='normal', help_text="Type of signature workflow: 'normal' (all parties sign), 'issuer_only' (only creator signs), 'informative' (no signatures needed).", max_length=20),
        ),
    ]
