# Generated by Django 5.0.6 on 2026-04-25 00:24

import gym_app.models.dynamic_document
from django.db import migrations, models


LOCKED_STATES = ('PendingSignatures', 'FullySigned', 'Rejected', 'Expired')


def backfill_letterhead_snapshots(apps, schema_editor):
    """Copy the currently configured letterhead onto the snapshot fields for
    every document already in a post-formalization state. This freezes those
    documents at the value they have at deploy time so subsequent letterhead
    changes by the creator do not alter previously formalized content.
    """
    from django.core.files.base import ContentFile

    DynamicDocument = apps.get_model('gym_app', 'DynamicDocument')

    qs = DynamicDocument.objects.filter(state__in=LOCKED_STATES)
    for document in qs.iterator():
        creator = getattr(document, 'created_by', None)

        if not document.letterhead_image_snapshot:
            source_img = document.letterhead_image or (
                creator.letterhead_image if creator and getattr(creator, 'letterhead_image', None) else None
            )
            if source_img:
                try:
                    source_img.open('rb')
                    try:
                        raw = source_img.read()
                    finally:
                        source_img.close()
                    base_name = source_img.name.rsplit('/', 1)[-1] if source_img.name else 'letterhead.png'
                    document.letterhead_image_snapshot.save(
                        f"snapshot_{document.pk}_{base_name}",
                        ContentFile(raw),
                        save=False,
                    )
                except (FileNotFoundError, ValueError, IOError):
                    pass

        if not document.letterhead_word_template_snapshot:
            source_doc = (
                document.letterhead_word_template
                if getattr(document, 'letterhead_word_template', None) else None
            )
            if not source_doc and creator and getattr(creator, 'letterhead_word_template', None):
                source_doc = creator.letterhead_word_template
            if source_doc:
                try:
                    source_doc.open('rb')
                    try:
                        raw = source_doc.read()
                    finally:
                        source_doc.close()
                    base_name = source_doc.name.rsplit('/', 1)[-1] if source_doc.name else 'letterhead.docx'
                    document.letterhead_word_template_snapshot.save(
                        f"snapshot_{document.pk}_{base_name}",
                        ContentFile(raw),
                        save=False,
                    )
                except (FileNotFoundError, ValueError, IOError):
                    pass

        document.save(update_fields=[
            'letterhead_image_snapshot',
            'letterhead_word_template_snapshot',
        ])


def noop_reverse(apps, schema_editor):
    """The forward backfill is non-destructive (only writes empty snapshot fields).
    Reversing simply drops the columns via the AddField reverse — no data loss
    of original ``letterhead_image`` / ``letterhead_word_template``.
    """
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0059_dynamicdocument_signature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='letterhead_image_snapshot',
            field=models.ImageField(blank=True, help_text='Copia congelada del membrete (PNG) al momento de formalizar. Inmutable: garantiza que el documento formalizado no varíe según quién lo descargue.', null=True, upload_to=gym_app.models.dynamic_document.letterhead_image_snapshot_path),
        ),
        migrations.AddField(
            model_name='dynamicdocument',
            name='letterhead_word_template_snapshot',
            field=models.FileField(blank=True, help_text='Copia congelada de la plantilla Word de membrete al momento de formalizar. Inmutable.', null=True, upload_to=gym_app.models.dynamic_document.document_letterhead_template_snapshot_path),
        ),
        migrations.RunPython(backfill_letterhead_snapshots, noop_reverse),
    ]
