# Generated by Django 5.0.6 on 2026-04-27 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0061_dynamicdocument_formalized_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Custom description for the alert email/notification.')),
                ('is_active', models.BooleanField(default=True)),
                ('notify_clients', models.BooleanField(default=True, help_text='If False, only the assigned lawyer is notified.')),
                ('notified_3_days', models.BooleanField(default=False)),
                ('notified_1_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='gym_app.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('signature_request', 'Solicitud de Firma'), ('signature_completed', 'Firma Completada'), ('signature_rejected', 'Firma Rechazada'), ('signature_expired', 'Firma Vencida'), ('signature_reopened', 'Firma Reabierta'), ('signature_reminder', 'Recordatorio de Firma'), ('process_alert', 'Alerta de Proceso'), ('general', 'General')], db_index=True, default='general', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('link_type', models.CharField(blank=True, default='', help_text="Resource type for navigation: 'process', 'document', 'service_request'.", max_length=50)),
                ('link_id', models.PositiveIntegerField(blank=True, help_text='PK of the linked resource.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'is_archived', 'is_deleted'], name='gym_app_not_user_id_26e25a_idx')],
            },
        ),
    ]
