# Generated by Django 5.0.6 on 2026-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0063_service_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefield',
            name='help_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
