# Generated by Django 5.2.14 on 2026-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0064_servicefield_help_text_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='allow_shared_edit',
            field=models.BooleanField(default=False, help_text='If True, lawyers other than the creator may edit this minuta (title, content, variables).'),
        ),
    ]
