# Generated by Django 5.2.14 on 2026-07-02 15:22

from django.db import migrations, models


def enable_shared_edit_on_existing(apps, schema_editor):
    """Backfill: sharing is the collaborative default, so existing minutas
    (created before the flag changed to default=True) become shared too."""
    DynamicDocument = apps.get_model('gym_app', 'DynamicDocument')
    DynamicDocument.objects.filter(allow_shared_edit=False).update(allow_shared_edit=True)


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0065_dynamicdocument_allow_shared_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdocument',
            name='allow_shared_edit',
            field=models.BooleanField(default=True, help_text='If True, lawyers other than the creator may edit this minuta (title, content, variables).'),
        ),
        migrations.RunPython(enable_shared_edit_on_existing, migrations.RunPython.noop),
    ]
