# Generated by Django 5.2.14 on 2026-07-06 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0066_allow_shared_edit_default_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('dynamic_documents', 'Archivos Jurídicos')], db_index=True, help_text='Module this tour belongs to.', max_length=50)),
                ('completed_at', models.DateTimeField(help_text='Last time the user completed or skipped the tour.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this tour progress record.', on_delete=django.db.models.deletion.CASCADE, related_name='tour_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'module_name'], name='gym_app_tou_user_id_d8cba5_idx')],
                'unique_together': {('user', 'module_name')},
            },
        ),
    ]
