# Generated by Django 5.2.14 on 2026-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0066_allow_shared_edit_default_true'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicerequest',
            name='unique_service_request_year_sequence',
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(fields=('tracking_year', 'tracking_sequence'), name='unique_service_request_year_sequence'),
        ),
    ]
