# Generated by Django 5.2.14 on 2026-07-07 00:03

import django.db.models.deletion
import django.utils.timezone
import gym_app.models.dynamic_document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0067_tourprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentvariable',
            name='summary_field',
            field=models.CharField(choices=[('none', 'Sin clasificar'), ('counterparty', 'Usuario / Contraparte'), ('object', 'Objeto'), ('value', 'Valor'), ('term', 'Plazo'), ('subscription_date', 'Fecha de suscripción'), ('start_date', 'Fecha de inicio'), ('end_date', 'Fecha de fin'), ('payment_installments', 'Forma de pago (N cuotas)')], default='none', help_text='Clasificación opcional para usar este campo en columnas resumen de las tablas.', max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='1-based installment number this record covers.')),
                ('file', models.FileField(help_text='Cuenta de cobro file (PDF, JPG, PNG or DOCX).', upload_to=gym_app.models.dynamic_document.payment_record_file_path)),
                ('original_name', models.CharField(blank=True, help_text='Original filename as uploaded by the user.', max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional installment amount.', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the uploader.', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Cargada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], db_index=True, default='uploaded', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Mandatory reason given by the lawyer on rejection.', null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Refreshed manually on every re-upload.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='Fully signed document this payment record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='gym_app.dynamicdocument')),
                ('uploaded_by', models.ForeignKey(help_text='User who performed the (last) upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('document', 'installment_number')},
            },
        ),
    ]
