# Generated by Django 5.2.14 on 2026-07-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0068_alter_documentvariable_summary_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indicates if the account is archived: blocked from every login method and excluded from active listings and notifications. Reversible.'),
        ),
    ]
