# Generated by Django 5.2.14 on 2026-07-07 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_managed_by(apps, schema_editor):
    """Existing documents are managed by their original creator."""
    DynamicDocument = apps.get_model('gym_app', 'DynamicDocument')
    DynamicDocument.objects.filter(managed_by__isnull=True).update(managed_by=F('created_by'))


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0069_user_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdocument',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='The lawyer currently responsible for managing this document. Defaults to the creator and changes on admin reassignment; created_by never changes (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_managed_by, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='process',
            name='lawyer',
            field=models.ForeignKey(help_text='The lawyer handling the case. PROTECT prevents deleting a lawyer who still owns processes; archive them instead.', on_delete=django.db.models.deletion.PROTECT, related_name='lawyer_processes', to=settings.AUTH_USER_MODEL),
        ),
    ]
