# Generated by Django 5.2.14 on 2026-07-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0067_servicerequest_year_sequence_unconditional_unique'),
        ('gym_app', '0070_dynamicdocument_managed_by_alter_process_lawyer'),
    ]

    operations = [
    ]
