from .user import UserSerializer, LegalUserLinkSerializer
from .process import CaseFileSerializer, StageSerializer, ProcessSerializer
from .legal_request import LegalRequestSerializer, LegalRequestFilesSerializer, LegalRequestTypeSerializer, LegalDisciplineSerializer