from .user import UserSerializer
from .process import CaseFileSerializer, StageSerializer, ProcessSerializer
from .legal_request import LegalRequestSerializer, LegalRequestFilesSerializer, LegalRequestTypeSerializer, LegalDisciplineSerializer
from .intranet_gym import LegalDocumentSerializer
from .dynamic_document import DynamicDocumentSerializer, DocumentVariableSerializer